config/routes.rb
Rails.application.routes.draw do
  resources :sequences
  resources :busstops
  resources :routes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/busstop.rb
class Busstop 
  include Neo4j::ActiveNode
  property :name, type: String
  property :latitude, type: Float
  property :longitude, type: Float
  # has_many :in, :comments, origin: :post
  has_many :out, :sequences, origin: :busstop
  has_many :out, :routes, type: :sequence

end

app/controllers/busstops_controller.rb
class BusstopsController < ApplicationController
  before_action :set_busstop, only: [:show, :edit, :update, :destroy]

  # GET /busstops
  # GET /busstops.json
  def index
    @busstops = Busstop.all
  end

  # GET /busstops/1
  # GET /busstops/1.json
  def show
  end

  # GET /busstops/new
  def new
    @busstop = Busstop.new
  end

  # GET /busstops/1/edit
  def edit
  end

  # POST /busstops
  # POST /busstops.json
  def create
    @busstop = Busstop.new(busstop_params)

    respond_to do |format|
      if @busstop.save
        format.html { redirect_to @busstop, notice: 'Busstop was successfully created.' }
        format.json { render :show, status: :created, location: @busstop }
      else
        format.html { render :new }
        format.json { render json: @busstop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /busstops/1
  # PATCH/PUT /busstops/1.json
  def update
    respond_to do |format|
      if @busstop.update(busstop_params)
        format.html { redirect_to @busstop, notice: 'Busstop was successfully updated.' }
        format.json { render :show, status: :ok, location: @busstop }
      else
        format.html { render :edit }
        format.json { render json: @busstop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /busstops/1
  # DELETE /busstops/1.json
  def destroy
    @busstop.destroy
    respond_to do |format|
      format.html { redirect_to busstops_url, notice: 'Busstop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_busstop
      @busstop = Busstop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def busstop_params
      params.require(:busstop).permit(:name, :latitude, :longitude)
    end
end

app/helpers/busstops_helper.rb
module BusstopsHelper
end

app/views/busstops/_form.html.erb
<%= form_with(model: busstop, local: true) do |form| %>
  <% if busstop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(busstop.errors.count, "error") %> prohibited this busstop from being saved:</h2>

      <ul>
      <% busstop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/busstops/edit.html.erb
<h1>Editing Busstop</h1>

<%= render 'form', busstop: @busstop %>

<%= link_to 'Show', @busstop %> |
<%= link_to 'Back', busstops_path %>

app/views/busstops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Busstops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @busstops.each do |busstop| %>
      <tr>
        <td><%= busstop.name %></td>
        <td><%= busstop.latitude %></td>
        <td><%= busstop.longitude %></td>
        <td><%= link_to 'Show', busstop %></td>
        <td><%= link_to 'Edit', edit_busstop_path(busstop) %></td>
        <td><%= link_to 'Destroy', busstop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Busstop', new_busstop_path %>

app/views/busstops/new.html.erb
<h1>New Busstop</h1>

<%= render 'form', busstop: @busstop %>

<%= link_to 'Back', busstops_path %>

app/views/busstops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @busstop.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @busstop.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @busstop.longitude %>
</p>

<%= link_to 'Edit', edit_busstop_path(@busstop) %> |
<%= link_to 'Back', busstops_path %>