config/routes.rb
Rails.application.routes.draw do
  resources :sequences
  resources :busstops
  resources :routes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sequence.rb
class Sequence 
  include Neo4j::ActiveNode
  property :sequence, type: Integer
  property :distance, type: Float
  property :next_busstop_id, type: String
  property :latitude, type: Float
  property :longitude, type: Float

  has_one :in, :busstop, type: :busstop
  has_one :in, :route, type: :route
  has_many :out, :sequences, rel_class: :Next

end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  before_action :set_sequence, only: [:show, :edit, :update, :destroy]

  # GET /sequences
  # GET /sequences.json
  def index
    @sequences = Sequence.all
  end

  # GET /sequences/1
  # GET /sequences/1.json
  def show
  end

  # GET /sequences/new
  def new
    @sequence = Sequence.new
  end

  # GET /sequences/1/edit
  def edit
  end

  # POST /sequences
  # POST /sequences.json
  def create
    @sequence = Sequence.new(sequence_params)

    respond_to do |format|
      if @sequence.save
        format.html { redirect_to @sequence, notice: 'Sequence was successfully created.' }
        format.json { render :show, status: :created, location: @sequence }
      else
        format.html { render :new }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sequences/1
  # PATCH/PUT /sequences/1.json
  def update
    respond_to do |format|
      if @sequence.update(sequence_params)
        format.html { redirect_to @sequence, notice: 'Sequence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sequence }
      else
        format.html { render :edit }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sequences/1
  # DELETE /sequences/1.json
  def destroy
    @sequence.destroy
    respond_to do |format|
      format.html { redirect_to sequences_url, notice: 'Sequence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sequence
      @sequence = Sequence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sequence_params
      params.require(:sequence).permit(:sequence, :distance, :next_busstop_id)
    end
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/views/sequences/_form.html.erb
<%= form_with(model: sequence, local: true) do |form| %>
  <% if sequence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sequence.errors.count, "error") %> prohibited this sequence from being saved:</h2>

      <ul>
      <% sequence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sequence %>
    <%= form.number_field :sequence %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.text_field :distance %>
  </div>

  <div class="field">
    <%= form.label :next_busstop_id %>
    <%= form.number_field :next_busstop_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sequences/edit.html.erb
<h1>Editing Sequence</h1>

<%= render 'form', sequence: @sequence %>

<%= link_to 'Show', @sequence %> |
<%= link_to 'Back', sequences_path %>

app/views/sequences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sequences</h1>

<table>
  <thead>
    <tr>
      <th>Sequence</th>
      <th>Distance</th>
      <th>Next busstop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sequences.each do |sequence| %>
      <tr>
        <td><%= sequence.sequence %></td>
        <td><%= sequence.distance %></td>
        <td><%= sequence.next_busstop_id %></td>
        <td><%= link_to 'Show', sequence %></td>
        <td><%= link_to 'Edit', edit_sequence_path(sequence) %></td>
        <td><%= link_to 'Destroy', sequence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sequence', new_sequence_path %>

app/views/sequences/new.html.erb
<h1>New Sequence</h1>

<%= render 'form', sequence: @sequence %>

<%= link_to 'Back', sequences_path %>

app/views/sequences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sequence:</strong>
  <%= @sequence.sequence %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @sequence.distance %>
</p>

<p>
  <strong>Next busstop:</strong>
  <%= @sequence.next_busstop_id %>
</p>

<%= link_to 'Edit', edit_sequence_path(@sequence) %> |
<%= link_to 'Back', sequences_path %>